# Generated by Django 5.1.3 on 2024-11-28 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='category',
            field=models.CharField(choices=[('workshop', 'Workshop'), ('meeting', 'Meeting'), ('webinar', 'Webinar'), ('conference', 'Conference')], default='meeting', max_length=20),
        ),
    ]
